apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host:  app1.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: servicio-app1
            port:
              number: 8080
  - host:  app2.example.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: servicio-app2
            port:
              number: 8080
  - host:  minio.dev.ed.dataspaceunit.linkeddata.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: comsrvs-minio
            port:
              number: 9000
  - host:  console.minio-s3.dev.ed.dataspaceunit.linkeddata.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: comsrvs-minio-console
            port:
              number: 9001